# Generated by Django 2.1.4 on 2019-05-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0045_auto_20190430_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='execution',
            name='execution_summary',
        ),
        migrations.AddField(
            model_name='execution',
            name='execution_returncode',
            field=models.IntegerField(default=0, verbose_name='Код возврата'),
        ),
        migrations.AddField(
            model_name='execution',
            name='test_summary',
            field=models.TextField(default='', verbose_name='Сводка'),
        ),
        migrations.AlterField(
            model_name='fntest',
            name='handler',
            field=models.CharField(choices=[('evc.init', 'evc: тривиальный'), ('evc.main', 'evc: основной'), ('evc.extd', 'evc: расширенный'), ('lss.init', 'lss: тривиальный'), ('lss.main', 'lss: основной'), ('lss.degn', 'lss: вырожденная матрица'), ('lss.insl', 'lss: несовместная матрица'), ('lss.degm', 'lss: вырожденный минор')], max_length=100, verbose_name='Обработчик'),
        ),
        migrations.AlterField(
            model_name='fntest',
            name='pattern',
            field=models.TextField(blank=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('OK', 'Задача решена'), ('TF', 'Тест провален'), ('WA', 'Неверный ответ'), ('NA', 'Ответ отсутствует'), ('TL', 'Превышено ограничение по времени'), ('ML', 'Превышено ограничение по памяти'), ('FE', 'Ошибка операции с плавающей точкой'), ('SF', 'Ошибка при работе с памятью'), ('RE', 'Ошибка выполнения'), ('CE', 'Ошибка компиляции'), ('UE', 'Ошибка кодировки'), ('PE', 'Ошибка комплектации'), ('UN', 'Посылка не проверена')], default='UN', max_length=2, verbose_name='Статус'),
        ),
    ]
